### ISSUE TITLE
Wrong license

### ISSUE THREAD

**Issue by mherrmann** [Iune/melbourne#16]
Hi,

Michael, creator of [fbs](https://build-system.fman.io) here. fbs is licensed under the GPLv3, which forces you to also put your project under the GPL. In other words, you can't use the MIT license. Kindly change it please.

Thanks!
Michael

**Comment by Iune** [comment]
I apologize for the issue — this is one of my first public projects and I hadn’t realized that licensing distinction. 

I will correct the issue this evening.

**Comment by Iune** [comment]
This should be corrected in 218df6e9e05464378825c48abdd75703d909a735.

Thank you for letting me know about the licensing requirement. Using `fbs` in this project really helped me create a graphical interface for the program. :)

**Comment by mherrmann** [comment]
No problem. I'm happy to hear you're finding fbs useful :-)
